### PR TITLE
Plex Movie Agent temporary fix

### PR DESCRIPTION
**Pull request by josh-gaby**
A workaround for the new Plex movie agent not returning imdb or tmdb ids.

One downside is that the matching function needs to be reverted to a search based on title and year since the Guid fields no longer contain the imdb/tmdb id (if using the new Plex Agent). This does give the possibility of a miss match but there isn't much that can be done about that.
_Edit:_
_The above downside is only relevant to libraries using the new plex agent, the title/year matching is only used as a fallback if there has been no match found using the imdb/tmdb id method._

This should be removed once the plexapi has been updated to include the required ids.

**Important:**
_The new Plex Movie Agent will only provide the IMDB and TMDB ids if the movie was added to your library or the metadata was refreshed on/after [PMS 1.20.1.3213](https://forums.plex.tv/t/plex-media-server/30447/360)_

### CODE REVIEW

**Comment by adamgot** [comment]
Thanks for your contribution!

I'd rather not break functionality for people still using the other agents (I think most people still), but it's great that people who want to use the new agent has something to try out in the meantime. Could you modify this so that it will use title (year) search as a fallback instead? I remember using that method early in development, and it was a real mess with big libraries especially.

**Comment by CrazyManInCincy** [comment]
2020-10-12 19:39:33,413 INFO:16 The Halloween Tree (1993)
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\runpy.
py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\runpy.
py", line 87, in _run_code
    exec(code, run_globals)
  File "plexlibrary\__main__.py", line 8, in <module>
    main()
  File "plexlibrary\plexlibrary.py", line 67, in main
    r.run(sort_only=args.sort_only, share_playlist_to_all=args.everyone)
  File "plexlibrary\recipe.py", line 691, in run
    missing_items, list_count = self._run(share_playlist_to_all=share_playlist_t
o_all)
  File "plexlibrary\recipe.py", line 632, in _run
    matching_items, missing_items, matching_total, nonmatching_idx, max_count =
self._get_matching_items(
  File "plexlibrary\recipe.py", line 183, in _get_matching_items
    imdb_id = self._get_imdb_from_plex_movie_agent(r)
  File "plexlibrary\recipe.py", line 228, in _get_imdb_from_plex_movie_agent
    imdb_id = self.tmdb.get_imdb_id(tmdb_id)
AttributeError: 'NoneType' object has no attribute 'get_imdb_id'

Not sure if it is error on my side or the script.

**Comment by josh-gaby** [comment]
@CrazyManInCincy looks like you haven't got a TMDB api key setup in your config and I wasn't checking for that, I've put a check in place but since that piece of code ran for you I don't think it would have given you a successful match anyway so I have also changed my pull request so that it doesn't rely on only the IMDB, that should mean that matches work with a TMDB or TVDB id as well (which is what I think you have going on with that movie).

**Comment by CrazyManInCincy** [comment]
> @CrazyManInCincy looks like you haven't got a TMDB api key setup in your config and I wasn't checking for that, I've put a check in place but since that piece of code ran for you I don't think it would have given you a successful match anyway so I have also changed my pull request so that it doesn't rely on only the IMDB, that should mean that matches work with a TMDB or TVDB id as well (which is what I think you have going on with that movie).

Will give it a try!

**Comment by josh-gaby** [comment]
> > @CrazyManInCincy looks like you haven't got a TMDB api key setup in your config and I wasn't checking for that, I've put a check in place but since that piece of code ran for you I don't think it would have given you a successful match anyway so I have also changed my pull request so that it doesn't rely on only the IMDB, that should mean that matches work with a TMDB or TVDB id as well (which is what I think you have going on with that movie).
> 
> Will give it a try!

Nice, let me know if its solved the issue for you

**Comment by CrazyManInCincy** [comment]
> > > @CrazyManInCincy looks like you haven't got a TMDB api key setup in your config and I wasn't checking for that, I've put a check in place but since that piece of code ran for you I don't think it would have given you a successful match anyway so I have also changed my pull request so that it doesn't rely on only the IMDB, that should mean that matches work with a TMDB or TVDB id as well (which is what I think you have going on with that movie).
> > 
> > 
> > Will give it a try!
> 
> Nice, let me know if its solved the issue for you

That fixed it! Thank you

**Comment by xfouloux** [comment]
hum i just cloned your repo, and it doesn't seem to do anything for me, is there a way to debug what it does ?

**Comment by josh-gaby** [comment]
> hum i just cloned your repo, and it doesn't seem to do anything for me, is there a way to debug what it does ?

Which branch did you clone? You'll need the plex-movie-agent-workaround branch, you'll also need to have had the library that's using the new Plex Agent refresh the metadata after the Plex version in my initial comment

**Comment by xfouloux** [comment]
Yup i did clone your repo : https://github.com/josh-gaby/python-plexlibrary/tree/plex-movie-agent-workaround
copied my recipes, config file and such, I refreshed my library too (again)
I have searched for a example movie, verified that there is Guid Imdb and tvdb new format,
When i run a test recipe, where the movie is part of a list, it does not pick it up.

Test movie is mulan tt4566758 (but i have other from these lists too)

```
2020-10-18 11:21:22,449 INFO:Running the recipe 'movies_trending'
2020-10-18 11:21:22,449 INFO:Retrieving the trakt list: https://api.trakt.tv/movies/trending?limit=2
2020-10-18 11:21:22,543 INFO:Retrieving the trakt list: https://api.trakt.tv/movies/watched/weekly?limit=100
2020-10-18 11:21:22,590 INFO:Retrieving the trakt list: https://api.trakt.tv/movies/trending?limit=50
2020-10-18 11:21:22,825 INFO:Retrieving the trakt list: https://api.trakt.tv/movies/watched/monthly?limit=150
2020-10-18 11:21:22,871 INFO:Retrieving the trakt list: https://api.trakt.tv/movies/watched/yearly?limit=500
2020-10-18 11:21:22,899 INFO:Trying to match with items from the 'Films' library
2020-10-18 11:21:35,344 INFO:Creating symlinks for 0 matching items in the library...
2020-10-18 11:21:35,344 INFO:Created symlinks for 0 new items:
2020-10-18 11:21:35,344 INFO:Creating the 'Films - Tendances' library in Plex...
2020-10-18 11:21:35,348 WARNING:Library already exists in Plex. Scanning the library...
2020-10-18 11:21:35,349 INFO:Waiting for metadata to finish downloading...
2020-10-18 11:21:35,353 INFO:Retrieving a list of items from the 'Films - Tendances' library in Plex...
2020-10-18 11:21:35,377 INFO:Setting the sort titles for the 'Films - Tendances' library...
2020-10-18 11:21:35,377 INFO:Removing symlinks for items which no longer qualify
2020-10-18 11:21:35,377 INFO:Removed symlinks for 0 items.
2020-10-18 11:21:35,377 INFO:Scanning the 'Films - Tendances' library...
2020-10-18 11:21:45,440 INFO:1 Terminator - Dark Fate (2019)
2020-10-18 11:21:45,580 INFO:2 Star Wars : L'Ascension de Skywalker (2019)
2020-10-18 11:21:45,584 INFO:3 La Reine des Neiges 2 (2019)
2020-10-18 11:21:45,705 INFO:4 Le Mans '66 (2019)
2020-10-18 11:21:45,721 INFO:5 Joker (2019)
2020-10-18 11:21:45,737 INFO:6 The Gentlemen (2019)
2020-10-18 11:21:45,862 INFO:7 La Chute du Président (2019)
2020-10-18 11:21:45,878 INFO:8 Captain Marvel (2019)
2020-10-18 11:21:46,003 INFO:9 Avengers : Endgame (2019)
2020-10-18 11:21:46,123 INFO:10 Aladdin (2019)
2020-10-18 11:21:46,127 INFO:11 À couteaux tirés (2019)
2020-10-18 11:21:46,131 INFO:12 The Invisible Man (2020)
2020-10-18 11:21:46,243 INFO:13 Artemis Fowl (2020)
2020-10-18 11:21:46,247 INFO:14 Scoob! (2020)
2020-10-18 11:21:46,360 INFO:15 Greyhound (2020)
2020-10-18 11:21:46,473 INFO:Number of items in the new library: 15
2020-10-18 11:21:46,473 INFO:Number of missing items: 226
2020-10-18 11:21:46,473 INFO:1          tt2222042       Love and Monsters (2020)
2020-10-18 11:21:46,473 INFO:2          tt4566758       Mulan (2020)
2020-10-18 11:21:46,473 INFO:3          tt1918734       2067 (2020)
2020-10-18 11:21:46,473 INFO:4          tt10682266      Hubie Halloween (2020)
2020-10-18 11:21:46,473 INFO:5          tt6723592       Tenet (2020)
2020-10-18 11:21:46,473 INFO:6          tt7846844       Enola Holmes (2020)
2020-10-18 11:21:46,473 INFO:7          tt8784956       Ava (2020)
2020-10-18 11:21:46,473 INFO:8          tt11771594      American Pie Presents: Girls Rules (2020)
2020-10-18 11:21:46,473 INFO:9          tt10804786      Welcome to Sudden Death (2020)
2020-10-18 11:21:46,473 INFO:10         tt1838556       Honest Thief (2020)
2020-10-18 11:21:46,473 INFO:11         tt4154796       Avengers: Endgame (2019)
2020-10-18 11:21:46,473 INFO:12         tt4532038       The War with Grandpa (2020)
2020-10-18 11:21:46,473 INFO:13         tt7286456       Joker (2019)
2020-10-18 11:21:46,473 INFO:14         tt7286966       Money Plane (2020)
2020-10-18 11:21:46,473 INFO:15         tt1502397       Bad Boys for Life (2020)
2020-10-18 11:21:46,473 INFO:16         tt7741388       The Scientist (2020)
2020-10-18 11:21:46,473 INFO:17         tt7713068       Birds of Prey (and the Fantabulous Emancipation of One Harley Quinn) (2020)
2020-10-18 11:21:46,473 INFO:18         tt6222118       The Doorman (2020)
2020-10-18 11:21:46,473 INFO:19         tt10324122      Secret Society of Second Born Royals (2020)
2020-10-18 11:21:46,473 INFO:20         tt7975244       Jumanji: The Next Level (2019)
2020-10-18 11:21:46,474 INFO:21         tt10059518      Unhinged (2020)
2020-10-18 11:21:46,474 INFO:22         tt12298506      Black Box (2020)
2020-10-18 11:21:46,474 INFO:23         tt1620981       The Addams Family (2019)
2020-10-18 11:21:46,474 INFO:24         tt8850222       Peninsula (2020)
2020-10-18 11:21:46,474 INFO:25         tt6320628       Spider-Man: Far from Home (2019)
2020-10-18 11:21:46,474 INFO:26         tt7737786       Greenland (2020)
2020-10-18 11:21:46,474 INFO:27         tt6751668       Parasite (2019)
2020-10-18 11:21:46,474 INFO:28         tt4682266       The New Mutants (2020)
2020-10-18 11:21:46,474 INFO:29         tt8367814       The Gentlemen (2020)
2020-10-18 11:21:46,474 INFO:30         tt11242218      Books of Blood (2020)
2020-10-18 11:21:46,474 INFO:31         tt11656172      Hard Kill (2020)
2020-10-18 11:21:46,474 INFO:32         tt12987894      American Murder: The Family Next Door (2020)
2020-10-18 11:21:46,474 INFO:33         tt4777008       Maleficent: Mistress of Evil (2019)
2020-10-18 11:21:46,474 INFO:34         tt6673612       Dolittle (2020)
2020-10-18 11:21:46,474 INFO:35         tt5113040       The Secret Life of Pets 2 (2019)
2020-10-18 11:21:46,474 INFO:36         tt6105098       The Lion King (2019)
2020-10-18 11:21:46,474 INFO:37         tt4520988       Frozen II (2019)
2020-10-18 11:21:46,474 INFO:38         tt13058290      BLACKPINK: Light Up the Sky (2020)
2020-10-18 11:21:46,474 INFO:39         tt10989808      Beckman (2020)
2020-10-18 11:21:46,474 INFO:40         tt1727824       Bohemian Rhapsody (2018)
2020-10-18 11:21:46,474 INFO:41         tt1950186       Ford v Ferrari (2019)
2020-10-18 11:21:46,474 INFO:42         tt7456310       Anna (2019)
2020-10-18 11:21:46,474 INFO:43         tt3224458       A Beautiful Day in the Neighborhood (2019)
2020-10-18 11:21:46,474 INFO:44         tt8946378       Knives Out (2019)
2020-10-18 11:21:46,474 INFO:45         tt5033998       Charlie's Angels (2019)
2020-10-18 11:21:46,474 INFO:46         tt6048922       Greyhound (2020)
2020-10-18 11:21:46,474 INFO:47         tt10065694      Antebellum (2020)
2020-10-18 11:21:46,474 INFO:48         tt11140488      The Wolf of Snow Hollow (2020)
2020-10-18 11:21:46,474 INFO:49         tt1070874       The Trial of the Chicago 7 (2020)
2020-10-18 11:21:46,474 INFO:50         tt6587640       Trolls World Tour (2020)
.....
.....
2020-10-18 11:21:46,480 INFO:225                tt4532826       Robin Hood (2018)
2020-10-18 11:21:46,480 INFO:226                tt0783640       The Last Full Measure (2020)
Done!
```

seems weird no ?

**Comment by josh-gaby** [comment]
@xfouloux that is weird, if the original version worked for you then this should too because my changes should only be used if the old method fails first.

Would you be able to share one of the recipes you're having issues with, maybe that DC one since that seems to possibly have a second issue?

**Comment by xfouloux** [comment]
Hey ! Thanks for this ! I know what went wrong, it's because i messed up with the plexapi lib and such, also i was sure the
```git checkout -b plex-movie-agent-workaround``` 
worked, but seems not and that was the culprit there
Your debug option is a nice addition and helps a lot, i also dockerized the app and use your repo/branch via the docker as it is way better =)

if this can help anyone to try out the PR

```
cd /usr/local/src/
mkdir docker-python-plexlibrary
cd docker-python-plexlibrary
vim Dockerfile
```
put into the file this
```
FROM python:3-buster

RUN \
# Update and and install python3 + pip for python-plexlibrary
    apt-get update && \
    apt-get install -y \
      python3-pip \
    && \
# Cleanup
    apt-get -y autoremove && \
    apt-get -y clean && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /tmp/* && \
    rm -rf /var/tmp/*
# Install python-plexlibrary requirements
RUN pip3 install plexapi requests trakt pyyaml ruamel.yaml lxml
```
save it then then you do 
```
docker build -t python-plexlibrary:stable
```
Your docker is created with libs needed and such
then you clone the repo and switch branch
```
cd ..
git clone https://github.com/josh-gaby/python-plexlibrary.git python-plexlibrary-workaround
cd python-plexlibrary-workaround
git checkout -b plex-movie-agent-workaround
git pull origin plex-movie-agent-workaround
```
Now you can copy from your current python-plexlibrary the config.yml file and the recipes folder
lets say my current folder for the project is python-plexlibrary
```
cd ..
cp /your/project/path/config.yml ./python-plexlibrary-workaround/
cp -R /your/project/path/recipes/ ./python-plexlibrary-workaround/
```
and now we run the container, binding the project workaround dir
```
docker run --network="cloudbox" --user="1000:1001" --rm -it -v /usr/local/src/python-plexlibrary-workaround:/scripts python-plexlibrary:stable python3 /scripts/plexlibrary RECIPE_NAME_OR_OPTION
```
replace RECIPE_NAME_OR_OPTION by the recipe you want to run or ```-l``` to list your recipes
replace or remove ```--network="cloudbox"``` as needed
replace or remove ```--user="1000:1001"``` as needed (it is uid:gid) to match the user that have the rights for the DIR where you want to do the symlinks, you can chack that by typing in your linux console
```
id USERNAME, or just id if you are logged with the user needed
```

You can put the command in a .sh like ```docker-python-plexlibrary.sh``` and put $1 at the end instead of the RECIPE_NAME_OR_OPTION
```
#!/bin/bash
docker run --network="cloudbox" --user="1000:1001" --rm -it -v /usr/local/src/python-plexlibrary-workaround:/scripts python-plexlibrary:stable python3 /scripts/plexlibrary $1
```
like this you can do 
```

**Comment by xfouloux** [comment]
to get back to our issue at hand, there you go with debug option for a small recipe :

```
2020-10-20 08:15:50,257 INFO:Running the recipe 'ghibli'
2020-10-20 08:15:50,258 INFO:Retrieving the trakt list: https://api.trakt.tv/users/draackje/lists/studio-ghibli-feature-films/items/movies
2020-10-20 08:15:50,340 INFO:Trying to match with items from the 'Films' library
2020-10-20 08:15:50,346 INFO:Checking 23 items for 500 max allowed matches.
2020-10-20 08:15:50,412 INFO:
2020-10-20 08:15:50,412 INFO:Using title search: Nausicaä of the Valley of the Wind (1984)
2020-10-20 08:15:50,488 INFO:trying 1985
2020-10-20 08:15:50,557 INFO:trying 1983
2020-10-20 08:15:50,627 INFO:No matches found
2020-10-20 08:15:50,693 INFO:
2020-10-20 08:15:50,693 INFO:Using title search: Castle in the Sky (1986)
2020-10-20 08:15:50,763 INFO:trying 1987
2020-10-20 08:15:50,839 INFO:trying 1985
2020-10-20 08:15:50,909 INFO:No matches found
2020-10-20 08:15:50,968 INFO:
2020-10-20 08:15:50,968 INFO:Using title search: Grave of the Fireflies (1988)
2020-10-20 08:15:51,046 INFO:trying 1989
2020-10-20 08:15:51,115 INFO:trying 1987
2020-10-20 08:15:51,181 INFO:No matches found
2020-10-20 08:15:51,240 INFO:
2020-10-20 08:15:51,240 INFO:Using title search: My Neighbor Totoro (1988)
2020-10-20 08:15:51,306 INFO:trying 1989
2020-10-20 08:15:51,373 INFO:trying 1987
2020-10-20 08:15:51,447 INFO:No matches found
2020-10-20 08:15:51,506 INFO:
2020-10-20 08:15:51,506 INFO:Using title search: Kiki's Delivery Service (1989)
2020-10-20 08:15:51,573 INFO:trying 1990
2020-10-20 08:15:51,638 INFO:trying 1988
2020-10-20 08:15:51,705 INFO:No matches found
2020-10-20 08:15:51,763 INFO:
2020-10-20 08:15:51,763 INFO:Using title search: Only Yesterday (1991)
2020-10-20 08:15:51,829 INFO:trying 1992
2020-10-20 08:15:51,904 INFO:trying 1990
2020-10-20 08:15:51,970 INFO:No matches found
2020-10-20 08:15:52,029 INFO:
2020-10-20 08:15:52,029 INFO:Using title search: Porco Rosso (1992)
2020-10-20 08:15:52,103 INFO:Matching plex:// to IMDB
2020-10-20 08:15:52,108 INFO:1 Porco Rosso (1992)
2020-10-20 08:15:52,167 INFO:
2020-10-20 08:15:52,167 INFO:Using title search: Ocean Waves (1993)
2020-10-20 08:15:52,234 INFO:trying 1994
2020-10-20 08:15:52,302 INFO:trying 1992
2020-10-20 08:15:52,374 INFO:No matches found
2020-10-20 08:15:52,433 INFO:
2020-10-20 08:15:52,434 INFO:Using title search: Pom Poko (1994)
2020-10-20 08:15:52,501 INFO:trying 1995
2020-10-20 08:15:52,568 INFO:trying 1993
2020-10-20 08:15:52,636 INFO:No matches found
2020-10-20 08:15:52,695 INFO:
2020-10-20 08:15:52,695 INFO:Using title search: Whisper of the Heart (1995)
2020-10-20 08:15:52,773 INFO:trying 1996
2020-10-20 08:15:52,841 INFO:trying 1994
2020-10-20 08:15:52,917 INFO:No matches found
2020-10-20 08:15:52,977 INFO:
2020-10-20 08:15:52,977 INFO:Using title search: Princess Mononoke (1997)
2020-10-20 08:15:53,055 INFO:trying 1998
2020-10-20 08:15:53,124 INFO:trying 1996
2020-10-20 08:15:53,191 INFO:No matches found
2020-10-20 08:15:53,251 INFO:
2020-10-20 08:15:53,251 INFO:Using title search: My Neighbors the Yamadas (1999)
2020-10-20 08:15:53,319 INFO:trying 2000
2020-10-20 08:15:53,386 INFO:trying 1998
2020-10-20 08:15:53,454 INFO:No matches found
2020-10-20 08:15:53,513 INFO:
2020-10-20 08:15:53,513 INFO:Using title search: Spirited Away (2001)
2020-10-20 08:15:53,583 INFO:trying 2002
2020-10-20 08:15:53,654 INFO:trying 2000
2020-10-20 08:15:53,722 INFO:No matches found
2020-10-20 08:15:53,782 INFO:
2020-10-20 08:15:53,782 INFO:Using title search: The Cat Returns (2002)
2020-10-20 08:15:53,851 INFO:trying 2003
2020-10-20 08:15:53,926 INFO:trying 2001
2020-10-20 08:15:53,996 INFO:No matches found
2020-10-20 08:15:54,057 INFO:
2020-10-20 08:15:54,057 INFO:Using title search: Howl's Moving Castle (2004)
2020-10-20 08:15:54,125 INFO:trying 2005
2020-10-20 08:15:54,194 INFO:trying 2003
2020-10-20 08:15:54,263 INFO:No matches found
2020-10-20 08:15:54,321 INFO:
2020-10-20 08:15:54,321 INFO:Using title search: Tales from Earthsea (2006)
2020-10-20 08:15:54,391 INFO:trying 2007
2020-10-20 08:15:54,464 INFO:trying 2005
2020-10-20 08:15:54,530 INFO:No matches found
2020-10-20 08:15:54,587 INFO:
2020-10-20 08:15:54,588 INFO:Using title search: Ponyo (2008)
2020-10-20 08:15:54,655 INFO:Matching plex:// to IMDB
2020-10-20 08:15:54,659 INFO:2 Ponyo (2008)
2020-10-20 08:15:54,717 INFO:
2020-10-20 08:15:54,717 INFO:Using title search: The Secret World of Arrietty (2010)
2020-10-20 08:15:54,785 INFO:trying 2011
2020-10-20 08:15:54,853 INFO:trying 2009
2020-10-20 08:15:54,920 INFO:No matches found
2020-10-20 08:15:54,977 INFO:
2020-10-20 08:15:54,977 INFO:Using title search: From Up on Poppy Hill (2011)
2020-10-20 08:15:55,043 INFO:trying 2012
2020-10-20 08:15:55,108 INFO:trying 2010
2020-10-20 08:15:55,174 INFO:No matches found
2020-10-20 08:15:55,234 INFO:
2020-10-20 08:15:55,235 INFO:Using title search: The Wind Rises (2013)
2020-10-20 08:15:55,302 INFO:trying 2014
2020-10-20 08:15:55,370 INFO:trying 2012
2020-10-20 08:15:55,435 INFO:No matches found
2020-10-20 08:15:55,492 INFO:
2020-10-20 08:15:55,492 INFO:Using title search: The Tale of the Princess Kaguya (2013)
2020-10-20 08:15:55,558 INFO:trying 2014
2020-10-20 08:15:55,632 INFO:trying 2012
2020-10-20 08:15:55,704 INFO:No matches found
2020-10-20 08:15:55,761 INFO:
2020-10-20 08:15:55,761 INFO:Using title search: When Marnie Was There (2014)
2020-10-20 08:15:55,831 INFO:trying 2015
2020-10-20 08:15:55,903 INFO:trying 2013
2020-10-20 08:15:55,989 INFO:No matches found
2020-10-20 08:15:56,070 INFO:
2020-10-20 08:15:56,070 INFO:Using title search: The Red Turtle (2016)
2020-10-20 08:15:56,155 INFO:trying 2017
2020-10-20 08:15:56,244 INFO:trying 2015
2020-10-20 08:15:56,333 INFO:No matches found
2020-10-20 08:15:56,333 INFO:Creating symlinks for 2 matching items in the library...
2020-10-20 08:15:56,346 INFO:Created symlinks for 0 new items:
2020-10-20 08:15:56,347 INFO:Creating the 'Dessins Animés - Ghibli' library in Plex...
2020-10-20 08:15:56,353 WARNING:Library already exists in Plex. Scanning the library...
2020-10-20 08:15:56,354 INFO:Waiting for metadata to finish downloading...
2020-10-20 08:16:01,372 INFO:Retrieving a list of items from the 'Dessins Animés - Ghibli' library in Plex...
2020-10-20 08:16:01,379 INFO:Setting the sort titles for the 'Dessins Animés - Ghibli' library...
2020-10-20 08:16:01,387 INFO:Removing symlinks for items which no longer qualify
2020-10-20 08:16:01,387 INFO:Removed symlinks for 0 items.
2020-10-20 08:16:01,387 INFO:Scanning the 'Dessins Animés - Ghibli' library...
2020-10-20 08:16:11,418 INFO:Number of items in the new library: 2
2020-10-20 08:16:11,418 INFO:Number of missing items: 21
2020-10-20 08:16:11,418 INFO:1          tt0087544       Nausicaä of the Valley of the Wind (1984)
2020-10-20 08:16:11,418 INFO:2          tt0092067       Castle in the Sky (1986)
2020-10-20 08:16:11,418 INFO:3          tt0095327       Grave of the Fireflies (1988)
2020-10-20 08:16:11,418 INFO:4          tt0096283       My Neighbor Totoro (1988)
2020-10-20 08:16:11,418 INFO:5          tt0097814       Kiki's Delivery Service (1989)
2020-10-20 08:16:11,418 INFO:6          tt0102587       Only Yesterday (1991)
2020-10-20 08:16:11,418 INFO:8          tt0108432       Ocean Waves (1993)
2020-10-20 08:16:11,418 INFO:9          tt0110008       Pom Poko (1994)
2020-10-20 08:16:11,418 INFO:10         tt0113824       Whisper of the Heart (1995)
2020-10-20 08:16:11,419 INFO:11         tt0119698       Princess Mononoke (1997)
2020-10-20 08:16:11,419 INFO:12         tt0206013       My Neighbors the Yamadas (1999)
2020-10-20 08:16:11,419 INFO:13         tt0245429       Spirited Away (2001)
2020-10-20 08:16:11,419 INFO:14         tt0347618       The Cat Returns (2002)
2020-10-20 08:16:11,419 INFO:15         tt0347149       Howl's Moving Castle (2004)
2020-10-20 08:16:11,419 INFO:16         tt0495596       Tales from Earthsea (2006)
2020-10-20 08:16:11,419 INFO:18         tt1568921       The Secret World of Arrietty (2010)
2020-10-20 08:16:11,419 INFO:19         tt1798188       From Up on Poppy Hill (2011)
2020-10-20 08:16:11,419 INFO:20         tt2013293       The Wind Rises (2013)
2020-10-20 08:16:11,419 INFO:21         tt2576852       The Tale of the Princess Kaguya (2013)
2020-10-20 08:16:11,419 INFO:22         tt3398268       When Marnie Was There (2014)
2020-10-20 08:16:11,419 INFO:23         tt3666024       The Red Turtle (2016)
Done!
```

**Comment by josh-gaby** [comment]
@xfouloux the plex-movie-agent-workaround branch doesn't do database lookups, that was just a simple workaround to get plexlibrary working again temporarily. People weren't so keen on going down the database lookup route so I've done that in a [separate branch](https://github.com/josh-gaby/python-plexlibrary/tree/direct-db-access) and haven't submitted a pull request to this repo. It is still a work in progress though.

**Comment by xfouloux** [comment]
Ohh ok !
So i guess the title search work on classic movies for me because having plex in french, it still has original title to search on i guess ?
But for jap movies, the xml as title in french and original title in JAP so the english movie from the trakt list doesn't match.

extract of XML from
tt0119698       Princess Mononoke (1997)
```
.....  Video ratingKey="20874" key="/library/metadata/20874" guid="plex://movie/5d7768246f4521001ea988b4" studio="Studio Ghibli" type="movie" title="Princesse Mononoké" titleSort="Princesse Mononoke" librarySectionTitle="Films" librarySectionID="2" librarySectionKey="/library/sections/2" originalTitle="もののけ姫" contentRating="Tous publics"  .........
```
I guess this would be the case for all users not having plex library in english ? and well title search would match almost ok on english movies, but not on any non english movies =)

About the DB patch, i'm not keen for it either, unless it can't be avoided for now, and it seems to be the best solution unfortunately.
Or we need to submit a forum post on plex to ask them to put back both GUID in the right place in the XML, but i won't count on that either

**Comment by josh-gaby** [comment]
> Testing now the DB branch
> indeed it works fine, without issue =) ! I guess for now it would do.
> Thanks for the work on both branches ! people have a choice to make now
> for those that want to test with docker change in my previous explanation edited to use the other branch

In your docker instructions you've missed setting the database path (db:'' option) for Plex in the config, I recommend running this on the same server as Plex to avoid using the the 'remote' option where possible.

**Comment by xfouloux** [comment]
indeed, good catch, it is updated.
also it seems the DB branch is not working well with TV show, so i'm currently running 1 container for the movies with your branch, and 1 container with the adamgot:master repo for tvshow

**Comment by xfouloux** [comment]
Can i issue on your fork then ?
Also, playlists aren't working too, maybe need just to merge with master ?

**Comment by josh-gaby** [comment]
> Can i issue on your fork then ?
> Also, playlists aren't working too, maybe need just to merge with master ?

Yeah, feel free to place an issue on my fork.

**Comment by xfouloux** [comment]
Hey, you need to open issue on your fork, if that's even possible ? Because right now, there is no issue tab.

**Comment by josh-gaby** [comment]
Done

**Comment by josh-gaby** [comment]
@xfouloux I added the TV series last night but I haven't had a chance to check out playlists yet, you'll need to install the requirements.txt again and do a pull request of the DB branch to get the changes

**Pull request closed without merging**
